version: '3.4'

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
        - "5432:5432"
    networks: 
        - financebook-network
    environment: 
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=admin
  financebook.finance.api:
    image: ${DOCKER_REGISTRY-}financebookfinanceapi
    container_name: FinanceBook.API
    build:
      context: .
      dockerfile: FinanceBook.Finance.API/Dockerfile
    networks: 
      - financebook-network
  
networks:
    financebook-network:
        name: financebook-network
        driver: bridge
  

